### ISSUE TITLE
An Htlm sample makes cuckoo crash

### ISSUE THREAD

**Issue by Nwinternights** [cuckoosandbox/community#332]
An html page without or with a fake extension makes cuckoo to crash. 
here is the code I used:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
	<html><head>
	<title>404 Not Found</title>
	</head><body>
	<h1>Not Found</h1>
	<p>The requested URL was not found on this server.</p>
	<p>Additionally, a 404 Not Found
	error was encountered while trying to use an ErrorDocument to handle the request.</p>
	<hr>
	<address>Apache/2.2.27 (Unix) mod_ssl/2.2.27 OpenSSL/0.9.8e-fips-rhel5 mod_bwlimited/1.4 Port 80</address>
	</body></html>
here is the md5: d901676729e2af7f58987d4e20d2bf5e ( I uploaded on malwr just for downloading)
here the traceback:
INFO: Guest is running Cuckoo Agent 0.7 (id=matrix02, ip=192.168.56.102)
2017-07-29 15:13:31,787 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=matrix02, ip=192.168.56.102, monitor=latest, size=3819928)
2017-07-29 15:13:32,123 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2017-07-29 15:13:32,124 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm matrix02
2017-07-29 15:13:33,618 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 698, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 499, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 394, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 480, in start_analysis
    self.post("/store", files=files, data=data)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 309, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.56.102:8000/store

**Comment by Nwinternights** [comment]
Im closing here im goin to open this issue on the main repo.
