### ISSUE TITLE
Failed to run 'on_call' of the creates_service signature

### ISSUE THREAD

**Issue by jcppkkk** [cuckoosandbox/community#378]
https://github.com/cuckoosandbox/community/blob/78d7741bb90053052efc7abdfa110321c3e36fd2/modules/signatures/windows/creates_service.py#L26

```
[cuckoo.core.plugins] ERROR: Failed to run 'on_call' of the creates_service signature
Traceback (most recent call last):
  File "cuckoo/cuckoo/core/plugins.py", line 417, in call_signature
    if not signature.matched and handler(*args, **kwargs):
  File "cuckoo_data/signatures/windows/creates_service.py", line 26, in on_call
    service_name = call["arguments"].get("service_name", "").lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by jbremer** [comment]
That's really weird ;-)
```
In [430]: call = {"arguments": {}}

In [431]: call["arguments"].get("service_name", "").lower() 
Out[431]: ''
```

**Comment by jcppkkk** [comment]
MD5 | 089a26fc433ef1f94a5071dd38731e1d
maybe somewhere cause service_name = None?
```
>>> call = {"arguments": {"service_name": None}}
>>> call["arguments"].get("service_name", "").lower() 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by jbremer** [comment]
Thanks for the PR!
