### ISSUE TITLE
Error when submitting Locky malware to windows 7 x86

### ISSUE THREAD

**Issue by ojasp** [cuckoosandbox/community#413]
The following error seems to be on windows/url_file.py:
2018-05-23 19:36:23,515 [cuckoo.core.plugins] ERROR: Failed to run 'on_complete' of the url_file signature
Traceback (most recent call last):
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 413, in call_signature
    if not signature.matched and handler(*args, **kwargs):
  File "/home/cuckoo/.cuckoo/signatures/windows/url_file.py", line 21, in on_complete
    if "Internet shortcut" not in self.file.get("type", ""):
AttributeError: 'URLFile' object has no attribute 'file'
2018-05-23 19:36:24,093 [cuckoo.core.scheduler] INFO: Task #22: reports generation completed

What am I missing?
Thanks,
Ojas

**Comment by doomedraven** [comment]
You can ignore that that is judt a signature fail, nothing critical

**Comment by RicoVZ** [comment]
Hi ojasp,

@doomedraven is correct. This is an error triggered by a signature.

https://github.com/cuckoosandbox/community/blob/master/modules/signatures/windows/url_file.py. 

Thanks for reporting it.
We will work on fixing it.

**Comment by RicoVZ** [comment]
@ojasp @doomedraven 
The signature was updated, and the error should not occur anymore. :smile:
