### ISSUE TITLE
ERROR when run "cuckoo community"

### ISSUE THREAD

**Issue by ebolanoso** [cuckoosandbox/community#433]
Hi, have this error when I run the command "cuckoo community"

(cuckoo) cuckoo@ubuntu:~$ cuckoo community
2018-08-09 12:19:22,350 [cuckoo.apps.apps] INFO: Downloading.. https://github.com/cuckoosandbox/community/archive/master.tar.gz
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/bin/cuckoo", line 11, in <module>
    sys.exit(main())
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/click/decorators.py", line 17, in 
new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/cuckoo/main.py", line 273, in community
    fetch_community(force=force, branch=branch, filepath=filepath)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/cuckoo/apps/apps.py", line 46, in fetch_community
    r = requests.get(URL % branch)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

Can you help me please?

regards

**Comment by doomedraven** [comment]
do you use any proxy?
